# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Carl Davis
tagline:             'An IT Tech'
description:         '"Have you tried turning it off and on again" - Roy Trenneman'
url:                 http://c-davis.co.uk
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Carl Davis
  url:               http://c-davis.co.uk
  email:             carl@c-davis.co.uk

# Custom vars
version:             0.0.1
